USE hbnb;

DROP TABLE IF EXISTS PlaceAmenity;
DROP TABLE IF EXISTS Amenity;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Place;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS User;
